# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arash/paya-programming-competition

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arash/paya-programming-competition

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arash/paya-programming-competition/CMakeFiles /home/arash/paya-programming-competition/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arash/paya-programming-competition/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named question-5

# Build rule for target.
question-5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 question-5
.PHONY : question-5

# fast build rule for target.
question-5/fast:
	$(MAKE) -f CMakeFiles/question-5.dir/build.make CMakeFiles/question-5.dir/build
.PHONY : question-5/fast

#=============================================================================
# Target rules for targets named question-7

# Build rule for target.
question-7: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 question-7
.PHONY : question-7

# fast build rule for target.
question-7/fast:
	$(MAKE) -f CMakeFiles/question-7.dir/build.make CMakeFiles/question-7.dir/build
.PHONY : question-7/fast

#=============================================================================
# Target rules for targets named question-2

# Build rule for target.
question-2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 question-2
.PHONY : question-2

# fast build rule for target.
question-2/fast:
	$(MAKE) -f CMakeFiles/question-2.dir/build.make CMakeFiles/question-2.dir/build
.PHONY : question-2/fast

#=============================================================================
# Target rules for targets named question-1-simple

# Build rule for target.
question-1-simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 question-1-simple
.PHONY : question-1-simple

# fast build rule for target.
question-1-simple/fast:
	$(MAKE) -f CMakeFiles/question-1-simple.dir/build.make CMakeFiles/question-1-simple.dir/build
.PHONY : question-1-simple/fast

#=============================================================================
# Target rules for targets named question-1

# Build rule for target.
question-1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 question-1
.PHONY : question-1

# fast build rule for target.
question-1/fast:
	$(MAKE) -f CMakeFiles/question-1.dir/build.make CMakeFiles/question-1.dir/build
.PHONY : question-1/fast

question-1/main.o: question-1/main.cpp.o

.PHONY : question-1/main.o

# target to build an object file
question-1/main.cpp.o:
	$(MAKE) -f CMakeFiles/question-1.dir/build.make CMakeFiles/question-1.dir/question-1/main.cpp.o
.PHONY : question-1/main.cpp.o

question-1/main.i: question-1/main.cpp.i

.PHONY : question-1/main.i

# target to preprocess a source file
question-1/main.cpp.i:
	$(MAKE) -f CMakeFiles/question-1.dir/build.make CMakeFiles/question-1.dir/question-1/main.cpp.i
.PHONY : question-1/main.cpp.i

question-1/main.s: question-1/main.cpp.s

.PHONY : question-1/main.s

# target to generate assembly for a file
question-1/main.cpp.s:
	$(MAKE) -f CMakeFiles/question-1.dir/build.make CMakeFiles/question-1.dir/question-1/main.cpp.s
.PHONY : question-1/main.cpp.s

question-1/simple-version.o: question-1/simple-version.cpp.o

.PHONY : question-1/simple-version.o

# target to build an object file
question-1/simple-version.cpp.o:
	$(MAKE) -f CMakeFiles/question-1-simple.dir/build.make CMakeFiles/question-1-simple.dir/question-1/simple-version.cpp.o
.PHONY : question-1/simple-version.cpp.o

question-1/simple-version.i: question-1/simple-version.cpp.i

.PHONY : question-1/simple-version.i

# target to preprocess a source file
question-1/simple-version.cpp.i:
	$(MAKE) -f CMakeFiles/question-1-simple.dir/build.make CMakeFiles/question-1-simple.dir/question-1/simple-version.cpp.i
.PHONY : question-1/simple-version.cpp.i

question-1/simple-version.s: question-1/simple-version.cpp.s

.PHONY : question-1/simple-version.s

# target to generate assembly for a file
question-1/simple-version.cpp.s:
	$(MAKE) -f CMakeFiles/question-1-simple.dir/build.make CMakeFiles/question-1-simple.dir/question-1/simple-version.cpp.s
.PHONY : question-1/simple-version.cpp.s

question-2/main.o: question-2/main.cpp.o

.PHONY : question-2/main.o

# target to build an object file
question-2/main.cpp.o:
	$(MAKE) -f CMakeFiles/question-2.dir/build.make CMakeFiles/question-2.dir/question-2/main.cpp.o
.PHONY : question-2/main.cpp.o

question-2/main.i: question-2/main.cpp.i

.PHONY : question-2/main.i

# target to preprocess a source file
question-2/main.cpp.i:
	$(MAKE) -f CMakeFiles/question-2.dir/build.make CMakeFiles/question-2.dir/question-2/main.cpp.i
.PHONY : question-2/main.cpp.i

question-2/main.s: question-2/main.cpp.s

.PHONY : question-2/main.s

# target to generate assembly for a file
question-2/main.cpp.s:
	$(MAKE) -f CMakeFiles/question-2.dir/build.make CMakeFiles/question-2.dir/question-2/main.cpp.s
.PHONY : question-2/main.cpp.s

question-5/main.o: question-5/main.cpp.o

.PHONY : question-5/main.o

# target to build an object file
question-5/main.cpp.o:
	$(MAKE) -f CMakeFiles/question-5.dir/build.make CMakeFiles/question-5.dir/question-5/main.cpp.o
.PHONY : question-5/main.cpp.o

question-5/main.i: question-5/main.cpp.i

.PHONY : question-5/main.i

# target to preprocess a source file
question-5/main.cpp.i:
	$(MAKE) -f CMakeFiles/question-5.dir/build.make CMakeFiles/question-5.dir/question-5/main.cpp.i
.PHONY : question-5/main.cpp.i

question-5/main.s: question-5/main.cpp.s

.PHONY : question-5/main.s

# target to generate assembly for a file
question-5/main.cpp.s:
	$(MAKE) -f CMakeFiles/question-5.dir/build.make CMakeFiles/question-5.dir/question-5/main.cpp.s
.PHONY : question-5/main.cpp.s

question-7/main.o: question-7/main.cpp.o

.PHONY : question-7/main.o

# target to build an object file
question-7/main.cpp.o:
	$(MAKE) -f CMakeFiles/question-7.dir/build.make CMakeFiles/question-7.dir/question-7/main.cpp.o
.PHONY : question-7/main.cpp.o

question-7/main.i: question-7/main.cpp.i

.PHONY : question-7/main.i

# target to preprocess a source file
question-7/main.cpp.i:
	$(MAKE) -f CMakeFiles/question-7.dir/build.make CMakeFiles/question-7.dir/question-7/main.cpp.i
.PHONY : question-7/main.cpp.i

question-7/main.s: question-7/main.cpp.s

.PHONY : question-7/main.s

# target to generate assembly for a file
question-7/main.cpp.s:
	$(MAKE) -f CMakeFiles/question-7.dir/build.make CMakeFiles/question-7.dir/question-7/main.cpp.s
.PHONY : question-7/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... question-5"
	@echo "... question-7"
	@echo "... question-2"
	@echo "... question-1-simple"
	@echo "... question-1"
	@echo "... question-1/main.o"
	@echo "... question-1/main.i"
	@echo "... question-1/main.s"
	@echo "... question-1/simple-version.o"
	@echo "... question-1/simple-version.i"
	@echo "... question-1/simple-version.s"
	@echo "... question-2/main.o"
	@echo "... question-2/main.i"
	@echo "... question-2/main.s"
	@echo "... question-5/main.o"
	@echo "... question-5/main.i"
	@echo "... question-5/main.s"
	@echo "... question-7/main.o"
	@echo "... question-7/main.i"
	@echo "... question-7/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

